<?php

namespace TransbankVendor;

// autoload_psr4.php @generated by Composer
$vendorDir = \dirname(__DIR__);
$baseDir = \dirname($vendorDir);
return array('Transbank\WooCommerce\WebpayRest\\' => array($baseDir . '/src'), 'Transbank\Plugin\\' => array($baseDir . '/shared'), 'TransbankVendor\\Transbank\\' => array($vendorDir . '/transbank/transbank-sdk/src'), 'TransbankVendor\Psr\Log\\' => array($vendorDir . '/psr/log/src'), 'TransbankVendor\Psr\Http\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'), 'TransbankVendor\Psr\Http\Client\\' => array($vendorDir . '/psr/http-client/src'), 'TransbankVendor\\Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'), 'TransbankVendor\GuzzleHttp\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'), 'TransbankVendor\GuzzleHttp\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'), 'TransbankVendor\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'));
