<?php

// autoload_static.php @generated by Composer
namespace Composer\Autoload;

class ComposerStaticInitf6e1557513b25646ab1b95c528dcf2b9
{
    public static $files = array('7b11c4dc42b3b3023073cb14e519683c' => __DIR__ . '/..' . '/ralouphie/getallheaders/src/getallheaders.php', '6e3fae29631ef280660b3cdad06f25a8' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php', '37a3dc5111fe8f707ab4c132ef1dbc62' => __DIR__ . '/..' . '/guzzlehttp/guzzle/src/functions_include.php');
    public static $prefixLengthsPsr4 = array('T' => array('Transbank\WooCommerce\WebpayRest\\' => 33, 'Transbank\Plugin\\' => 17, 'TransbankVendor\\Transbank\\' => 10), 'P' => array('Psr\Log\\' => 8, 'Psr\Http\Message\\' => 17, 'Psr\Http\Client\\' => 16), 'M' => array('TransbankVendor\\Monolog\\' => 8), 'G' => array('GuzzleHttp\Psr7\\' => 16, 'GuzzleHttp\Promise\\' => 19, 'TransbankVendor\\GuzzleHttp\\' => 11));
    public static $prefixDirsPsr4 = array('Transbank\WooCommerce\WebpayRest\\' => array(0 => __DIR__ . '/../..' . '/src'), 'Transbank\Plugin\\' => array(0 => __DIR__ . '/../..' . '/shared'), 'TransbankVendor\\Transbank\\' => array(0 => __DIR__ . '/..' . '/transbank/transbank-sdk/src'), 'Psr\Log\\' => array(0 => __DIR__ . '/..' . '/psr/log/src'), 'Psr\Http\Message\\' => array(0 => __DIR__ . '/..' . '/psr/http-factory/src', 1 => __DIR__ . '/..' . '/psr/http-message/src'), 'Psr\Http\Client\\' => array(0 => __DIR__ . '/..' . '/psr/http-client/src'), 'TransbankVendor\\Monolog\\' => array(0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog'), 'GuzzleHttp\Psr7\\' => array(0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src'), 'GuzzleHttp\Promise\\' => array(0 => __DIR__ . '/..' . '/guzzlehttp/promises/src'), 'TransbankVendor\\GuzzleHttp\\' => array(0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src'));
    public static $classMap = array('Composer\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php');
    public static function getInitializer(\Composer\Autoload\ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = \Composer\Autoload\ComposerStaticInitf6e1557513b25646ab1b95c528dcf2b9::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = \Composer\Autoload\ComposerStaticInitf6e1557513b25646ab1b95c528dcf2b9::$prefixDirsPsr4;
            $loader->classMap = \Composer\Autoload\ComposerStaticInitf6e1557513b25646ab1b95c528dcf2b9::$classMap;
        }, null, \Composer\Autoload\ClassLoader::class);
    }
}
